### ISSUE TITLE
UX: CLI text based UI for init, reconcile and render

### ISSUE THREAD

**Issue by ezodude** [appvia/kev#199]
As a developer, I'd like simple & concise command line interactions, that get out of the way but provide the information that I need when I need it.

**Solution**

Design the text UI for the CLI to create messaging that's easy to scan and understand using a set of simple reusable UI components.

This will unify copy across all commands.

**Inspiration**

- [Designing CLI tools](https://medium.com/@emilygoldfein/designing-cli-tools-a8e0858f606e)  by Emily Goldfein

- [CL Eye Catching UIs Video](https://www.youtube.com/watch?v=3d15R-Nx57c) by James Bowes

- [CL Eye Catching UIs Slides](https://github.com/jbowes/cl-eye-catching-uis) by James Bowes

- [spinner](https://github.com/briandowns/spinner)

- [tablewriter](https://github.com/olekukonko/tablewriter)

**Comment by marcinc** [comment]
@ezodude I think we addressed some of the above in the recent work? Closing for now but please reopen if this still needs looking at.

**Comment by ezodude** [comment]
@marcinc Yup, we have addressed this. We no longer need the ticket.
