### ISSUE TITLE
Reconcile doesn't resolve # of replicas

### ISSUE THREAD

**Issue by marcinc** [appvia/kev#272]
It looks like reconcile doesn't resolve all the config options correctly. `replicas` being one example. This could be related to recent work around compacting configuration options so worth looking at.

When I change the service name in source compose it'd reflect that change in environment override files, however, changes made to service parameters don't seem to propagate.

**Comment by ezodude** [comment]
@marcinc Interesting. I think that's what's it meant to do.

So, changing a service's name equates to ...
- Remove service with old name.
- Add service with new name.

There's no way for us to tell right now that you've `Just` changed the names. For all intents and purposes the renamed service is a new service.

The old line by line diff solution could've sometimes made what you wanted to happen but not always.

We should discuss (maybe tomorrow).

**Comment by ezodude** [comment]
@marcinc I'm closing this ticket as we resolved to better communicate Reconcile rules, See #275
