### ISSUE TITLE
Rolling updates should only target Deployments

### ISSUE THREAD

**Issue by ezodude** [appvia/kev#527]
## What

The rolling update strategy should only target the Deployment workload type.

## Why

The current rolling update strategy targets any K8s workload type, including StatefulSets.

This is incorrect as different workload types require varying config that we currently do no take into account when generating K8s manifests.

**Comment by chriswalker** [comment]
No action required; after discussion with @marcinc this doesn't appear to be an issue. In the case of StatefulSet workloads (which are the only other workload type besides Deployments that we explicitly apply update strategies to), we're defaulting to `StatefulSetUpdateStrategy` structs with no additional configuration, so k8s will apply defaults here.
