### ISSUE TITLE
Changes in docker compose file not applied to all environment overrides

### ISSUE THREAD

**Issue by chriswalker** [appvia/kev#573]
### Short issue description
Running through the [Getting Started](https://github.com/appvia/kev/blob/master/docs/tutorials/getting-started-with-kev.md) tutorial and updating the `docker-compose.yaml` to include the MySQL DB service and associated volume, I expected to see corresponding changes to the all compose override files (`local` and `stage` as per the tutorial) and generated k8s files after running `kev render`. The render step only updated the `dev` override + k8s files, and not `local` and `stage` - these overrides were missing service details for the DB, and StatefulSet/PersistentVolumeClaim files for k8s.

Kev version:
OS (Linux/Mac/Windows..): Mac OS 11.4
Docker Compose version:1.29.2
Kubernetes version: 1.21
Kubernetes distribution (e.g. GKE, EKS, ...): Docker Desktop

### How can we reproduce the issue?
1. Run through the tutorial up to adding the DB service, and make the required MySQL/volume changes to `docker-compose.yaml`
2. Run `kev render`
3. Check reconciled compose override files and generated k8s files - only the dev overrides are initially updated
4. Running `kev render` again will reconcile `local`, but leave `stage`
5. Running `kev render` a final time will reconcile `stage`

**Comment by ezodude** [comment]
Thanks for the heads @chriswalker!
