### ISSUE TITLE
Review and change the naming convention of the artefacts produced by the program

### ISSUE THREAD

**Issue by marcinc** [appvia/kev#584]
Consider making changes to the files naming convention to make it more meaningful, and still reduce naming conflicts as much as possible.

**Comment by chriswalker** [comment]
Plan is to change from (for example) `docker-compose.kev.dev.yaml` and so on to `docker-compose.env.dev.yaml`. This will require changes to:

* All test fixture filenames
* Documentation (tutorials and README

`kev.yaml` will also change names, but this is still under discussion.

**Comment by marcinc** [comment]
Resolved by #588
